### ISSUE TITLE
failed to unpack truncated message

### ISSUE THREAD

**Issue by jungle-boogie** [mehrdadrad/mylg#42]
Hi,

I'm getting this on a few different nodes:

```
ns/italy/arezzo> dig github.com
Trying to query server: 62.149.132.2 italy arezzo
dns: failed to unpack truncated message
```

This bypasses `/etc/resolve.conf` and uses whatever node I select, right?

**Comment by mehrdadrad** [comment]
mylg tries to get all DNS records that's why it shows truncated for this domain. if you try it with dig command through your OS you will see the same error

```
sh-3.2# dig github.com any
;; Truncated, retrying in TCP mode.
;; Connection to 192.168.0.1#53(192.168.0.1) for github.com failed: connection refused.
```

if you try a small query by mylg it should be workd:

```
local> dig github.com A
Trying to query server (udp): 192.168.0.1  your local dns server
;; opcode: QUERY, status: NOERROR, id: 30045
;; flags: qr rd ra;
github.com.	283	IN	A	192.30.253.112
github.com.	283	IN	A	192.30.253.113
;; Query time: 21 ms

;; CHAOS CLASS BIND
version.bind.	0	CH	TXT	"Version: main/17458"
hostname.bind.	0	CH	TXT	"chwoca-dns-cac-307.(none)"
```

 I think the best workaround is adding a fall back to TCP if truncated issue happened then if TCP didn't answer, the mylg changes the query ANY to only A records to have a better size of the result and preventing truncated issue.
